---
title: "progress-report-rljensen20"
output: html_document
---

```{r}
library(rvest)
```
```{r}
library(Lahman)
```

```{r}
HallOfFame
```


```{r}
url <- "https://www.baseball-reference.com/awards/hof_2025.shtml"
html <- read_html(url)
tables <- html_table(html)
head(tables)


data <- tables[[1]]
actual_col_names <- data[1, ]
colnames(data) <- make.names(actual_col_names, unique = TRUE)
data <- data[-1, ]
data

names(data)[[2]] <- "Name"
data
```

```{r}
data_numeric <- data %>% 
  mutate(
    across(c(YoB, Votes, HOFm, HOFs, Yrs, WAR, WAR7,JAWS, Jpos,G,AB,R,H,HR,RBI,SB,BB,BA,
             OBP, SLG, OPS, OPS., W, L, ERA, ERA., WHIP, G.1, GS, SV, IP, H.1, HR.1, BB.1, SO, 
             ), parse_number)
  ) 

```

```{r}
data_cleaned <- data_numeric %>% 
  mutate(
    Name =  gsub("X-", "", Name)
  )
```


```{r}
library(dplyr)
```


```{r}
people_needed_info <- People %>%
  mutate(Name = paste(nameFirst, nameLast)) %>%
  select(playerID, Name)

```
```{r}
data_joined <- left_join(data_cleaned, people_needed_info, by = "Name")
data_joined

```
 
```{r}
hof_2024 <- data_joined %>%
  mutate(
    yearID = 2024,
    votedBy = "BBWAA",
    ballots = NA,  
    needed = NA,   
    inducted = ifelse(Votes >= 75, "Y", "N"), 
    category = "Player",
    needed_note = NA
  ) %>%
  select(playerID, yearID, votedBy, ballots, needed, Votes, inducted, category, needed_note)

HallOfFame_updated <- bind_rows(HallOfFame, hof_2024)

write.csv(HallOfFame_updated, "HallOfFame.csv", row.names = FALSE)
```









