---
title: "progress-report-AnalynSeeman"
author: "Analyn Seeman"
date: "2025-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}

library(rvest)

url <- "https://www.baseball-reference.com/awards/hof_2024.shtml"
html <- read_html(url)
tables <- html_table(html, fill = TRUE)
data <- tables[[1]]

```
```{r}

actual_col_names <- data[1, ]
colnames(data) <- actual_col_names
data <- data[-1, ]

```


```{r}
library(dplyr)

data <- data %>%
  select(Name, Votes) %>%
  mutate(
    Votes = as.numeric(Votes),
    Name = gsub("X-", "", Name)
  )

```

```{r}

library(Lahman)

peopleneeded <- People %>%
  mutate(Name = paste(nameFirst, nameLast)) %>%
  select(playerID, Name)

unmatched <- anti_join(data, peopleneeded, by = "Name")
print(unmatched)

data$Name <- iconv(data$Name, to = "ASCII//TRANSLIT")

data_joined <- left_join(data, peopleneeded, by = "Name")

hof_2024 <- data_joined %>%
  mutate(
    yearID = 2024,
    votedBy = "BBWAA",
    ballots = NA,  # Replace with actual number if known
    needed = NA,   # Replace with actual number if known
    inducted = ifelse(Votes >= 75, "Y", "N"),  # Assuming 75% is needed
    category = "Player",
    needed_note = NA
  ) %>%
  select(playerID, yearID, votedBy, ballots, needed, Votes, inducted, category, needed_note)

HallOfFame_updated <- bind_rows(HallOfFame, hof_2024)

write.csv(HallOfFame_updated, "HallOfFame.csv", row.names = FALSE)

```

